image_registry: ghcr.io
image_registry_api_url: https://ghcr.io/v2
image_registry_api_token_url: https://ghcr.io/token?service=ghcr.io&scope=repository
image_repository: aicage/aicage
image_base_repository: aicage/aicage-image-base
default_image_base: ubuntu
version_check_image: ghcr.io/aicage/aicage-image-util:latest
