---
name: Build, Test, and Publish Docker Images

"on":
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - "base-images/**"
      - "final-images/**"
      - ".env"
      - ".github/workflows/build-images.yml"
  pull_request:
    paths:
      - "base-images/**"
      - "final-images/**"
      - ".env"
      - ".github/workflows/build-images.yml"
  workflow_dispatch: {}

jobs:
  build:
    name: Build, test and push all images
    runs-on: ubuntu-latest
    env:
      BUILDX_BAKE_ALLOW: fs=/tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: "Test: Set up Python"
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "3.x"

      - name: "Test: Install lint deps"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: "Test: Run linters (yamllint, ruff, pymarkdown)"
        run: |
          yamllint .
          ruff check .
          pymarkdown --config .pymarkdown.json scan .

      - name: "Test: Set up Buildx"
        uses: docker/setup-buildx-action@v3.11.1
        with:
          driver: docker-container

      - name: "Test: Setup BATS testing framework"
        uses: mig4/setup-bats@v1.2.0

      - name: "Test: Build base images for tests"
        run: |
            base-images/scripts/build-all.sh \
            --platform linux/amd64

      - name: "Test: Run smoke suites on base images"
        run: |
            base-images/scripts/test-all.sh

      - name: "Test: Build final images for tests"
        run: |
          final-images/scripts/build-all.sh \
            --platform linux/amd64

      - name: "Test: Run smoke suites on final images"
        run: |
          final-images/scripts/test-all.sh

      - name: "Publish: Set up QEMU"
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-qemu-action@v3.7.0

      - name: "Publish: Log in to Docker Hub"
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Publish: Build base images"
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          base-images/scripts/build-all.sh \
            --version "${{ github.ref_name }}" \
            --push

      - name: "Publish: Build and push all images"
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          final-images/scripts/build-all.sh \
            --version "${{ github.ref_name }}" \
            --push
